### ISSUE TITLE
Absolute paths in INI breaking ProxAllium after relocation

### ISSUE THREAD

**Issue by Songersoft** [DcodingTheWeb/ProxAllium#1]
I relocated my ProxAllium on my hard drive (I moved the folder)

After the move ProxAllium ini needed updated.  Just letting you know.  Maybe if ProxAllium doesn't find Tor it will recheck the root folder and update the ini.

**Comment by TheDcoder** [comment]
Ah! An excellent find! ProxAllium automatically writes the absolute location of the tor executable in the `ini` file, maybe I can make it use relative paths...

I'll see what I can do, thanks for the report!

**Comment by TheDcoder** [comment]
I am reluctant to fix this problem because I am planning to make an automatic Tor management system which would download/detect/update Tor automatically for the user, this feature would make this bug redundant.

For anyone with this problem, they can just delete `config.ini` and `config.torrc` so that ProxAllium can regenerate them with the new paths... and of course it can also be done manually by changing the paths in the INI and torrc files 😉

**Comment by TheDcoder** [comment]
I have just pushed a [commit](https://github.com/DcodingTheWeb/ProxAllium/commit/3c642bf5ae0c18be42aab830f92d87d8d481be45) which fixes this bug by using relative paths in `config.ini`. The fix will be included in the next release.

You can [download the fixed source code](https://github.com/DcodingTheWeb/ProxAllium/archive/3c642bf5ae0c18be42aab830f92d87d8d481be45.zip) if you want to test it out, also includes new features 😉
