### ISSUE TITLE
Error: Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by rx8driver** [DcodingTheWeb/ProxAllium#12]
Using Tor Expert Bundle 0.4.6.7 and running:
Windows 11 Pro
Version	21H2
OS build	22000.160
Experience	Windows Feature Experience Pack 1000.22000.160.0

I experience an error where ProxAllium reports it is unable to identify Tor's version. When attempting to regenerate the Tor config from the Options menu an error is encountered:

"Autolt Error" in the dialog window header
Line 13984 (File "C:\ProxAllium\ProxAllium.exe"):
Error: Subscript used on non-accessible variable.

Clicking OK on the dialog closes the program.

**Comment by TheDcoder** [comment]
Thanks for reporting the issue, I see that the latest version of Tor Browser still ships with `0.4.5.10 (git-fd74f7628eba2525)`, so I'd suggest using that while I look into the issue.

**Comment by TheDcoder** [comment]
> Using Tor Expert Bundle 0.4.6.7

@rx8driver Where did you get this version? I checked the official download page and it only links to `0.4.5.10`. Did you compile it yourself?

**Comment by rx8driver** [comment]
No, this version is from the Tor Expert Bundle for windows...

**Comment by TheDcoder** [comment]
@rx8driver Can you double-check? The latest version of Tor Browser and Expert Bundle both use the version I mentioned. If you are indeed using a newer version, please provide me with the link to get it.

**Comment by rx8driver** [comment]
Sure, here's the link for the Windows package: https://www.torproject.org/download/tor/

You'll see the link below the one for the source code....

**Comment by TheDcoder** [comment]
@rx8driver Ah, I think you got confused about the version because the source is more up to date compared to the expert bundle, if you examine the link to download, you will notice that it says **`tor-win32-0.4.5.10.zip`** at the end.

I need your help to determine the issue as I cannot reproduce it here, can you run this command in PowerShell or Command Prompt: `tor.exe --version > version.txt`

You need to do it in the same folder as `tor.exe`, to do that hold `Shift` and right-click in the folder and an option to open PS or CMD will appear.

After running the command, a file called `version.txt` will be created, **please attach it your next reply**.

Here is an example from my machine:
```
C:\Users\John\Desktop\Tor Browser\Browser\TorBrowser\Tor>tor.exe --version > version.txt

C:\Users\John\Desktop\Tor Browser\Browser\TorBrowser\Tor>type version.txt
Tor version 0.4.5.10 (git-fd74f7628eba2525).
```

**Comment by TheDcoder** [comment]
I think the issue might be due to something else, I fixed an out of bounds access bug in another part of the code: 4146827eaacf213ae28286906cd0dc2146d2e32f

Can you see if that fixes the issue for you? You can run the source code directly with AutoIt or you can ask me to provide you with a test build, let me know.

**Comment by rx8driver** [comment]
I checked it in PowerShell and you're correct, it reports the version as 0.4.5.10--sorry for the confusion!

**Comment by rx8driver** [comment]
> I think the issue might be due to something else, I fixed an out of bounds access bug in another part of the code: 4146827eaacf213ae28286906cd0dc2146d2e32f
> 
> Can you see if that fixes the issue for you? You can run the source code directly with AutoIt or you can ask me to provide you with a test build, let me know.

Just clone the repo and run it through autolt, right?

**Comment by rx8driver** [comment]
I had to stop my existing running tor service due to port conflicts (no worries) but I am up and running :) whatever you did seems to have worked and proxallium will successfully configure and launch using either the TBB or the Tor Expert Bundle.... Thanks very much man!

**Comment by rx8driver** [comment]
I've never played with AutoIt before, I think I'll tinker around and see if I can't just build it myself and then properly install it..... Sounds like a fun way to spend an hour lol

**Comment by TheDcoder** [comment]
Thanks for testing, glad to know that the issue is solved!

Building ProxAllium isn't complex, you can use the "Compile with Options" menu item after right-clicking on the source file. There is no installation per-se, you just move the main executable into a different folder and package it, just like how I do it in the releases :)
