### ISSUE TITLE
Support for bridges and pluggable transports

### ISSUE THREAD

**Issue by Ahmed0425** [DcodingTheWeb/ProxAllium#2]
Tor is censored in my country so I need bridges features
Also I need entrynode and exitnode feature (if possible)
thanks for reading

**Comment by TheDcoder** [comment]
Hello Ahmed! I am surprised to see that someone is using ProxAllium beside me and my friends!

I will definitely add support for bridges in the upcoming update, entry node and exit node too. Infact, exit nodes are already supported internally, you can open `config.ini` and add a new setting called `exit_node_country_code` under the `tor_config` section. Use a country code as the value and Tor will connect to an exit node from that country. Don't forget to delete `config.torrc` after modifying the settings so that ProxAllium will regenerate it with the new options.

For the time being I can assist you in getting ProxAllium working with bridges by adding custom settings to `config.torrc`. Just drop by in IRC ("chat" in the website) or send me an email if you are interested.

Thanks for using ProxAllium!

**Comment by Ahmed0425** [comment]
Thanks ^_^ I'll indeed try it a bit deeper :)
In fact, I've heard about your program from here
https://www.reddit.com/r/onions/comments/7hx2u6/is_it_possible_to_make_tor_as_a_vpn_or_proxy_on_pc/
Is that comment writer you or one of your friends?

**Comment by TheDcoder** [comment]
Thanks for posting the link, the comment writer is not one of my friends, interesting to see that people know about it 😄

**Comment by TheDcoder** [comment]
I am currently working on the GUI for bridges, here is a preview 😄:
![autoit3_2017-12-10_15-44-40](https://user-images.githubusercontent.com/6347576/33803943-3c74ac56-ddc1-11e7-8c03-45842fa1d744.png)

I am expecting to have bridges done by tonight, do you have any suggestions?

**Comment by Ahmed0425** [comment]
Are those obfs4 bridges?

**Comment by TheDcoder** [comment]
They are vanilla bridges without pluggable transports, I am focusing on getting them to work first, before experimenting with pluggable transports like `obfs4` or `meek`. I am guessing that you will need to use them since Tor is censored for you.

**Comment by Ahmed0425** [comment]
unfortunately vanilla bridges are censored as well -_- (although pluggable transports are not censored)
I'm so sorry but I won't be able to test them :(

**Comment by TheDcoder** [comment]
No worries, I will be adding support for pluggable transports too, once I am done with vanilla bridges.

**Comment by TheDcoder** [comment]
Getting bridges done by "tonight" as mentioned in my previous comment didn't happen, I got busy.

But support for bridges has been added in 480a68d2a9fbc2a1efa5ce405ccc256a2cfd351a 😄. I will look into pluggable transports and see if I can get them working!

**Comment by TheDcoder** [comment]
I have some good news and some bad news. I have experimented with the obfs4 pluggable transport and it worked! 😀

I did not change any code, I just added a custom configuration line in `config.torrc` which tells Tor to support obfs4 bridges.

obfs4 is a separate program which proxies Tor's traffic, so we need to ship that with ProxAllium too, not a big deal. But here is the catch:
When Tor is started, it also starts obfs4 and connects to it to relay the network traffic to it, but when Tor is stopped, the obfs4 instance/process doesn't end, therefore when Tor is started again there is a conflict of ports because of the already running obfs4 and Tor won't start until this process is killed. I have been looking to workarounds but still haven't implemented any.

@Ahmed0425 or anyone who is interested can test this by downloading the special build with obfs4 support. Just remember that once Tor is started, it won't start again until `obfs4proxy.exe` is killed again, one can simply restart to kill it or running this command: `taskkill /im obfs4proxy.exe /f /t`. Also, don't forget to regenerate Tor configuration after configuring bridges!

[ProxAllium-382ee60-volatile_Tor-0.3.1.9.zip](https://github.com/DcodingTheWeb/ProxAllium/files/1565311/ProxAllium-382ee60-volatile_Tor-0.3.1.9.zip) (`zip` because GitHub doesn't support uploading `7z` in bug reports...)

**Comment by TheDcoder** [comment]
I have added support for the `obfs` and `scramblesuit` pluggable transports in 9164607647aef319be20c006933d512c61b43b91, all issues mentioned in this ticket should be addressed.

ProxAllium now supports bridges and major pluggable transports to bypass censorship 😀

**Comment by RaXorX** [comment]
When I set the exitnode in config.ini and delete the torrc file, ProxAllium is always stuck at Bootstrapped 0% with this message 

"We've been configured to use (or avoid) nodes in certain countries, and we need GEOIP information to figure out which ones they are.
Trying to build a circuit, please wait...
Bootstrapped 0% (starting): Starting"

Any resolution to this?

**Comment by TheDcoder** [comment]
@RaXorX It sounds like you don't have the `geoip` files configured properly, the latest version of ProxAllium doesn't automatically find these for you unfortunately (I forgot to add auto-detection for these files).

So you will have to manually set the `geoip4_file` and `geoip6_file` keys in `config.ini` to the paths of `geoip` and `geoip6` files, they are distributed with both the Tor Expert Bundle and the Tor Browser Bundle.

**Comment by xp499** [comment]
Please, @TheDcoder, related to all the main topic of this issue, reopen this to add support for snowflake PT bridge.

Newly relevant extracted config lines from TBB .torrc config are:
`ClientTransportPlugin snowflake exec TorBrowser\Tor\PluggableTransports\snowflake-client.exe -url https://snowflake-broker.torproject.net.global.prod.fastly.net/ -front cdn.sstatic.net -ice stun:stun.l.google.com:19302,stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478`
and
`Bridge snowflake 192.0.2.3:1 2B280B23E1107BB62ABFC40DDCC8824814F80A72`

snowflake-client.exe binary is now included on TBB stable.
