### ISSUE TITLE
Add (Open minimized) and (minimize to taskbar) options

### ISSUE THREAD

**Issue by Ahmed0425** [DcodingTheWeb/ProxAllium#4]
Hi!
You told us a way to make it open during startup and added (minimize to tray) option but those two options are useful as the first is useful if it is automatically opened during startup and the second option is useful if it doesn't start at startup and the user want at least to remember that proxallium is opened and doesn't run tor by mistake because he didn't notice the tray icon
of course (minimize to tray) is optional as well :)

**Comment by TheDcoder** [comment]
I agree with you, I have thought about these options a long time ago, but didn't gave them much importance since everything was good enough, hopefully you guys will see this in v0.4 😄.

P.S
> doesn't run tor by mistake

ProxAllium shows you a message if it is already running 😉

**Comment by TheDcoder** [comment]
An option for automatically starting with Windows has been added in 93af376ee8c2b62521dbcdf59a6515ef199f2df0

I will work on a "Start Minimized" option, then we can complete this feature request.

**Comment by TheDcoder** [comment]
Added an option to start minimized in 9923579cbe4b995927f97f67449f9320a0bbf18c 😄

Obligatory screenshot:
![ProxAllium with the new options](https://user-images.githubusercontent.com/6347576/36340454-313bf02e-1403-11e8-8b4a-43f7eadeda69.png)

**Comment by xp499** [comment]
Related to all this newly added functionality, please @TheDcoder add also a switch to make selecting "Minimize to system tray" an optional feature. Thank you.

**Comment by TheDcoder** [comment]
Can you tell me why you want ProxAllium to be minimized to the taskbar? It does't do much so in my opinion it is better if it is hidden away in the tray.

**Comment by xp499** [comment]
> 
> 
> Can you tell me why you want ProxAllium to be minimized to the taskbar? It does't do much so in my opinion it is better if it is hidden away in the tray.

Because i need to have opened and minimized console Tor Output window in the taskbar to check what's the current status of Tor binary.

Debug, warns and info console messages do not show up in main window log and minimize to system tray's behaviour it is also affecting to that window when you try to minimize it. That, under my point of view, or needs, should be optional behaviour as when you minimize console Tor Output window it just dissapear and/or minimize also to system tray icon where there's no easy nor trivial way to restore it in one click if you have/want to have/need to have application's icon tray hidden inside Window's system tray overflow menu.

It is nice to have "Start minimized" option and the application's system tray icon as a reminder that the app is running in the background but you may understand that there's also people needs' that also match working with the app at foreground while still also need to minimize it and restore it from the taskbar in one click regardless of app's icon tray.

On another example: Stopping or starting Tor manually whenever it is needed to or wanted to while having system app icon try hidden on the overflow menu. Restore window it does not take just one click also in this case.
