### ISSUE TITLE
Display ProxAllium version in window

### ISSUE THREAD

**Issue by leafcutterant** [DcodingTheWeb/ProxAllium#7]
I know that ProxAllium isn't updated that often, but when I checked for a new release, it was not straightforward to find out which version I had.  Displaying the version somewhere in the window (e.g. the header, `ProxAllium 0.4`) could be useful.

Thanks!

**Comment by TheDcoder** [comment]
Thanks for the suggestion, I agree that it should be easy to check for the current version. Maybe the [tray menu](https://download.tuxfamily.org/proxallium/screenshots/v0.4/tray.png) is a good place for the version? It already shows the program name at the top, I could easily append the version string to it :smile:

I am not sure if it is worth implementing at the moment since I am not planning to update this version of ProxAllium anymore. If you have read the [thanks note](https://proxallium.org/download/#thanks) at the download page, you will know that I am planning to rewrite in C for a few reasons, so I doubt this feature will be useful currently...

I have not yet started working on the code for new ProxAllium, but I am planning to start soon and make an initial release with CLI interface only, for both Linux and Windows. GUI will follow that release, thanks to [IUP](http://webserver2.tecgraf.puc-rio.br/iup/) it is fairly easy to write a cross-platform GUI with native looks!

**Comment by TheDcoder** [comment]
I am closing this as 8d7c62b satisfies this feature request somewhat... the version is displayed when using the `--version` switch in the next-gen ProxAllium which is written in C :slightly_smiling_face:

I am hoping to spend more time on developing the new version but I have been busy with work. But I have switched to Linux as my main operating system now, so there is more motivation for me to complete a working version of the cross-platform C version so that I can use my program again
