### ISSUE TITLE
Contains a ransomware virus (according to 15 virus scanners)

### ISSUE THREAD

**Issue by rebroad** [DcodingTheWeb/ProxAllium#8]
According to virustotal, the latest release contains a ransomware virus.

**Comment by Ahmed0425** [comment]
WOW seriously? 🤨
the program is written in Autoit and it cannot even make a basic trojan 😮
however, I'll try to rescan and see

**Comment by Ahmed0425** [comment]
Just checked it ... it's obviously a false positive
if you are still worried, you can download autoit from their site [here](https://www.autoitscript.com/site/autoit/downloads/) and take a look of the capabilities of autoit yourself
also you can compile it yourself and recheck but remember to remove the UPX Compression stub option because this is a general reason for most false positive files

**Comment by TheDcoder** [comment]
@rebroad I just [scanned](https://www.virustotal.com/gui/file/ee33cfe4925df34f11edced842e8d9d1cae729e84afbf9dfe087a762aaad2105/detection) the executable from the latest release, I see many "trojan" detections but not ransomware, are you sure ProxAllium contains the ransomware?

Most of the detections are either generic or based on heuristics, this is common for programs made in AutoIt, see: https://www.autoitscript.com/forum/topic/34658-are-my-autoit-exes-really-infected/

> also you can compile it yourself and recheck but remember to remove the UPX Compression stub option because this is a general reason for most false positive files

@Ahmed0425 The latest version should be compiled without UPX, and it is also possible to directly run the source code (script) in AutoIt without compiling 😄

**Comment by rebroad** [comment]
@TheDcoder 20 out of 69 virus engines is a pretty reliable indicator that it contains malware from my experience so far. It's very unusual for 20 engines to all make a false positive. Perhaps 1 or 2 engines would do this at the most, but I've never seen it happen with 20 so far.

**Comment by TheDcoder** [comment]
@rebroad 1 or 2 detections is very uncommon with compiled AutoIt executables, there are often more false positive detections (~5-15). The recent increase in the detections might have to do something with this: https://blog.trendmicro.com/trendlabs-security-intelligence/autoit-compiled-negasteal-agent-tesla-ave-maria-delivered-via-malspam/

Every time some malware uses AutoIt in its exploit chain, it will usually trigger higher detection rates for all AutoIt executables, this is because compiled AutoIt scripts have a lot in common, infact, the only thing which is not common is the embedded script inside the `.exe` file, everything else is just the same `AutoIt3.exe` script interpreter which is used in all compiled programs.

Anti-virus programs depend on the "signature" of a file and the signatures of all AutoIt executables are pretty similar, so this is where the problem lies. When they blacklist some malware in a compiled script, they also pretty much add many other innocent scripts to their detection lists too.

I am going to close this issue as you seem to be only suspicious about the ransomware, feel free to reply with any more information that you have.
