### ISSUE TITLE
Feature request: Option to not use proxy setting of windows

### ISSUE THREAD

**Issue by fakhamatia** [DcodingTheWeb/ProxAllium#9]
When I use VPNs ProxAllium and Tor disconnected and show message `Proxy Client: unable to connect to IP:Port ("general SOCKS server failure")`, When VPN disconnect Tor Connect again.
Please add a setting to ProxAllium for change proxy option to not use VPNs proxies.

**Comment by TheDcoder** [comment]
Have you manually configured any proxy settings for Tor? (not the same as starting a VPN)

**Comment by F50Ci37Y** [comment]
> Have you manually configured any proxy settings for Tor? (not the same as starting a VPN)

No, I didn't touch it

**Comment by TheDcoder** [comment]
Then I am not sure why Tor is showing you the `Proxy Client: unable to connect to IP:Port ("general SOCKS server failure")` message. According to your observations, it is due to the VPN, however that doesn't make much sense to me as the VPN should not be blocking Tor. Does Tor browser work well when the VPN is turned on?

> Please add a setting to ProxAllium for change proxy option to not use VPNs proxies.

As far as I know, there is no standard option in Tor which I can configure for it to bypass VPN, so this is not possible. I am going to mark this feature request as "invalid" for that reason.
